name: Build Android (Capacitor Debug)

on:
  workflow_dispatch:
  push:
    paths:
      - "package.json"
      - "package-lock.json"
      - "capacitor.config.*"
      - "www/**"
      - "android/**"
      - ".github/workflows/android-debug.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      CAPACITOR_SKIP_ASK: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Hvis du bygger web med et rammeverk, kjør build her:
      # - name: Build web
      #   run: npm run build

      - name: Capacitor sync android
        run: npx cap sync android

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Assemble debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
