name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Cordova
        run: npm i -g cordova@12
      - name: Install Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
      - name: Accept licenses + install platforms/build-tools
        run: |
          yes | sdkmanager --licenses >/dev/null
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
      - name: Install deps
        run: npm ci
      - name: Add android platform
        run: npx cordova platform add android
      - name: Build debug APK
        env:
          GRADLE_OPTS: "-Dorg.gradle.caching=false -Dkotlin.daemon.jvm.options=-Xmx2g"
        run: npm run build
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ravn-debug-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
