name: Build Cordova Android (Debug)

on:
  workflow_dispatch:
  push:
    paths:
      - "config.xml"
      - "package.json"
      - "www/**"
      - ".github/workflows/android-debug.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Cordova
        run: npm i -g cordova

      - name: Install dependencies
        run: npm ci

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Add Android platform
        run: cordova platform add android@14.0.1

      - name: Build debug APK
        run: cordova build android --debug --no-telemetry --no-interactive

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: platforms/android/app/build/outputs/apk/debug/*.apk
