name: Build Android (Capacitor Debug)

on:
  workflow_dispatch:
  push:
    paths:
      - "www/**"
      - "package.json"
      - "package-lock.json"
      - "capacitor.config.*"
      - ".github/workflows/capacitor-android-debug.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm ci || npm i

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platform + build-tools
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Create Android project if missing
        run: |
          test -d android || npx cap add android --skip-npm

      - name: Sync native files
        run: npx cap sync android

      - name: Build Debug APK
        working-directory: android
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2g"
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
